
name: practice

on:
  push:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: check out linter
        uses: actions/checkout@v4

      - name: run linter
        run: echo "code quality check passed "

  
  training:
    needs: linter 

    if: |
      github.ref=='refs/heads/main' &&
      contains(github.event.head_commit.message, '[run-train]')

    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4
      - name: python setup
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'
      - name: install dependeces
        run: pip install -r requirements.txt

      - name: run training
        run: python training.py
      
      - name: generate error log
        if: failure()
        run: echo "generate error log"> error_log.txt

      - name: upload error log if failure
        if: failure()
        uses: actions/upload-artifact@v4
        with: 
         name: error log
         path: error_log.txt
      
      - name: cleaning gpu
        if: always()
        run: echo"training gpu"

      

