
name: practice 
on:
  push:
  
jobs:
  
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: check out 
        uses: actions/checkout@v4
      - name: run linter
        run: echo "qualit code checked"


  image-build:
    needs: linter
    if: |
     github.ref=='refs/heads/main' &&
     contains(github.event.head_commit.message,'[build-image]')

    runs-on: ubuntu-latest
    steps:
      - name: check out 
        uses: actions/checkout@v4
      - name: docker build
        run: docker build -t my-app .
      
      - name: generte error log
        if: failure()
        run: echo "generate error log" > error_log.txt

      - name: upload artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with: 
         name: error log
         path: error_log.txt

      - name: clean up
        if: always()
        run: echo "cleaning up"
 
     
     
