
name: Practice 
on:
  push:

jobs:
  
  linter-job: 
    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v4

      - name: run linter job
        run: echo "code quality check passed"


  Training:
    needs: linter-job
    
    if: |
      github.ref=='refs/heads/main'&&
      contains(github.event.head_commit.message,'[run-train]')

    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v4
      - name: python set up
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'

      - name: Install dependeces
        run: pip install -r requirements.txt

      - name: run trainig
        run: python training.py
      
      - name: Generate error log
        run: echo "if failure geenrate error log" > error_log.txt

      - name: training failure
        if: failure()
        uses: actions/upload-artifact@v4
        with: 
          name: error-log
          path: error_log.txt
        
      - name: clean-up gpu rescources
        if: always()
        run: echo "cleaning gpu resources"




